theme: jekyll-theme-minimal

title: Timin's world
description: no kids, 3 money

collections:
  pages:
    output: true
    permalink: /:path/
  hokkaido:
    output: true
  spring travels:
    output: true

collection_order:
  - hokkaido
  - spring travels
  - pages


permalink: /:path/

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
